version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    volumes:
      - laravel-demo-code:/var/www/html
    networks:
      - reverse-proxy
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_HOST}`)"

  db:
    image: mariadb
    networks:
      - db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  mutagen:
    image: alpine:latest
    container_name: ${PROJECT_NAME}-mutagen
    volumes:
      - laravel-demo-code:/var/www/html
    command: tail -f /dev/null

networks:
  reverse-proxy:
    external: true
  db:

volumes:
  laravel-demo-code:
